apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: booking
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: db-url