apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: booking
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: db-url
            - name: GOOGLE_CLIENT_ID
              value: 362406102359-frmsjn6et0551pciju1li4mep62thmse.apps.googleusercontent.com 