// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AddEvent Add an event
	// (POST /api/v1/add-event)
	AddEvent(c *fiber.Ctx) error
	// AdminAddEventGroup Add an event group
	// (POST /api/v1/admin/add-event-group)
	AdminAddEventGroup(c *fiber.Ctx) error
	// AdminAddEvents Add events
	// (POST /api/v1/admin/add-events)
	AdminAddEvents(c *fiber.Ctx) error
	// AdminListContacts List contacts
	// (GET /api/v1/admin/contacts)
	AdminListContacts(c *fiber.Ctx) error
	// AdminDuplicateEventGroup Duplicate an event group
	// (POST /api/v1/admin/duplicate-event-group)
	AdminDuplicateEventGroup(c *fiber.Ctx) error
	// AdminSearchEventGroups Search event groups by title
	// (GET /api/v1/admin/event-groups/search)
	AdminSearchEventGroups(c *fiber.Ctx, params AdminSearchEventGroupsParams) error
	// AdminGetEventGroup Get an event group for duplication
	// (GET /api/v1/admin/event-groups/{eventGroupID})
	AdminGetEventGroup(c *fiber.Ctx, eventGroupID string) error

	// (GET /api/v1/admin/events)
	GetApiV1AdminEvents(c *fiber.Ctx, params GetApiV1AdminEventsParams) error

	// (GET /api/v1/admin/events/{eventID})
	GetApiV1AdminEventsEventID(c *fiber.Ctx, eventID string) error

	// (POST /api/v1/admin/events/{eventID}/approve-event)
	AdminEventApprove(c *fiber.Ctx, eventID string) error

	// (POST /api/v1/admin/events/{eventID}/cancel-event)
	AdminEventCancel(c *fiber.Ctx, eventID string) error
	// AdminUpdateEventDates Update event dates and times
	// (PUT /api/v1/admin/events/{eventID}/dates)
	AdminUpdateEventDates(c *fiber.Ctx, eventID string) error
	// AdminSetEventKeyholders Set event keyholders
	// (PUT /api/v1/admin/events/{eventID}/keyholders)
	AdminSetEventKeyholders(c *fiber.Ctx, eventID string) error

	// (POST /api/v1/admin/events/{eventID}/request-documents)
	AdminEventRequestDocuments(c *fiber.Ctx, eventID string) error

	// (POST /api/v1/admin/events/{eventID}/set-rate)
	AdminEventSetRate(c *fiber.Ctx, eventID string) error

	// (GET /api/v1/admin/invoices/by-id/{invoiceID})
	AdminGetInvoiceByID(c *fiber.Ctx, invoiceID string) error

	// (POST /api/v1/admin/invoices/by-id/{invoiceID}/mark-as-paid)
	AdminMarkInvoicePaid(c *fiber.Ctx, invoiceID string) error

	// (GET /api/v1/admin/invoices/for-events)
	AdminGetInvoicesForEvents(c *fiber.Ctx, params AdminGetInvoicesForEventsParams) error
	// AdminListKeyholders List keyholders
	// (GET /api/v1/admin/keyholders)
	AdminListKeyholders(c *fiber.Ctx) error
	// AdminCreateKeyholder Create a keyholder
	// (POST /api/v1/admin/keyholders)
	AdminCreateKeyholder(c *fiber.Ctx) error
	// AdminUpdateKeyholder Update a keyholder
	// (PUT /api/v1/admin/keyholders/{keyholderID})
	AdminUpdateKeyholder(c *fiber.Ctx, keyholderID openapi_types.UUID) error

	// (GET /api/v1/admin/rates)
	AdminGetRates(c *fiber.Ctx) error

	// (POST /api/v1/admin/rates)
	AdminCreateRate(c *fiber.Ctx) error

	// (PUT /api/v1/admin/rates/{rateID})
	AdminUpdateRate(c *fiber.Ctx, rateID string) error

	// (POST /api/v1/admin/send-invoice)
	AdminSendInvoice(c *fiber.Ctx) error

	// (GET /api/v1/events)
	GetApiV1Events(c *fiber.Ctx, params GetApiV1EventsParams) error

	// (GET /api/v1/events.ics)
	GetEventsICS(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c *fiber.Ctx, next fiber.Handler) error

// AddEvent operation middleware
func (siw *ServerInterfaceWrapper) AddEvent(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AddEvent(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminAddEventGroup operation middleware
func (siw *ServerInterfaceWrapper) AdminAddEventGroup(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminAddEventGroup(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminAddEvents operation middleware
func (siw *ServerInterfaceWrapper) AdminAddEvents(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminAddEvents(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminListContacts operation middleware
func (siw *ServerInterfaceWrapper) AdminListContacts(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminListContacts(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminDuplicateEventGroup operation middleware
func (siw *ServerInterfaceWrapper) AdminDuplicateEventGroup(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminDuplicateEventGroup(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminSearchEventGroups operation middleware
func (siw *ServerInterfaceWrapper) AdminSearchEventGroups(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminSearchEventGroupsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "title" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "title", query, &params.Title, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter title: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminSearchEventGroups(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminGetEventGroup operation middleware
func (siw *ServerInterfaceWrapper) AdminGetEventGroup(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "eventGroupID" -------------
	var eventGroupID string

	err = runtime.BindStyledParameterWithOptions("simple", "eventGroupID", c.Params("eventGroupID"), &eventGroupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter eventGroupID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminGetEventGroup(c, eventGroupID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetApiV1AdminEvents operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AdminEvents(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1AdminEventsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", query, &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter from: %w", err).Error())
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", query, &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter to: %w", err).Error())
	}

	// ------------- Optional query parameter "contact" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "contact", query, &params.Contact, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contact: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetApiV1AdminEvents(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetApiV1AdminEventsEventID operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AdminEventsEventID(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "eventID" -------------
	var eventID string

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", c.Params("eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter eventID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetApiV1AdminEventsEventID(c, eventID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminEventApprove operation middleware
func (siw *ServerInterfaceWrapper) AdminEventApprove(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "eventID" -------------
	var eventID string

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", c.Params("eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter eventID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminEventApprove(c, eventID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminEventCancel operation middleware
func (siw *ServerInterfaceWrapper) AdminEventCancel(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "eventID" -------------
	var eventID string

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", c.Params("eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter eventID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminEventCancel(c, eventID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminUpdateEventDates operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateEventDates(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "eventID" -------------
	var eventID string

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", c.Params("eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter eventID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminUpdateEventDates(c, eventID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminSetEventKeyholders operation middleware
func (siw *ServerInterfaceWrapper) AdminSetEventKeyholders(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "eventID" -------------
	var eventID string

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", c.Params("eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter eventID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminSetEventKeyholders(c, eventID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminEventRequestDocuments operation middleware
func (siw *ServerInterfaceWrapper) AdminEventRequestDocuments(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "eventID" -------------
	var eventID string

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", c.Params("eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter eventID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminEventRequestDocuments(c, eventID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminEventSetRate operation middleware
func (siw *ServerInterfaceWrapper) AdminEventSetRate(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "eventID" -------------
	var eventID string

	err = runtime.BindStyledParameterWithOptions("simple", "eventID", c.Params("eventID"), &eventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter eventID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminEventSetRate(c, eventID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminGetInvoiceByID operation middleware
func (siw *ServerInterfaceWrapper) AdminGetInvoiceByID(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "invoiceID" -------------
	var invoiceID string

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceID", c.Params("invoiceID"), &invoiceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter invoiceID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminGetInvoiceByID(c, invoiceID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminMarkInvoicePaid operation middleware
func (siw *ServerInterfaceWrapper) AdminMarkInvoicePaid(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "invoiceID" -------------
	var invoiceID string

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceID", c.Params("invoiceID"), &invoiceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter invoiceID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminMarkInvoicePaid(c, invoiceID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminGetInvoicesForEvents operation middleware
func (siw *ServerInterfaceWrapper) AdminGetInvoicesForEvents(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminGetInvoicesForEventsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "events" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "events", query, &params.Events, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter events: %w", err).Error())
	}

	// ------------- Optional query parameter "eventGroup" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "eventGroup", query, &params.EventGroup, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter eventGroup: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminGetInvoicesForEvents(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminListKeyholders operation middleware
func (siw *ServerInterfaceWrapper) AdminListKeyholders(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminListKeyholders(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminCreateKeyholder operation middleware
func (siw *ServerInterfaceWrapper) AdminCreateKeyholder(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminCreateKeyholder(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminUpdateKeyholder operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateKeyholder(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "keyholderID" -------------
	var keyholderID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "keyholderID", c.Params("keyholderID"), &keyholderID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter keyholderID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminUpdateKeyholder(c, keyholderID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminGetRates operation middleware
func (siw *ServerInterfaceWrapper) AdminGetRates(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminGetRates(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminCreateRate operation middleware
func (siw *ServerInterfaceWrapper) AdminCreateRate(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminCreateRate(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminUpdateRate operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateRate(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "rateID" -------------
	var rateID string

	err = runtime.BindStyledParameterWithOptions("simple", "rateID", c.Params("rateID"), &rateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter rateID: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminUpdateRate(c, rateID)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// AdminSendInvoice operation middleware
func (siw *ServerInterfaceWrapper) AdminSendInvoice(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.AdminSendInvoice(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetApiV1Events operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Events(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1EventsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", query, &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter from: %w", err).Error())
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", query, &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter to: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetApiV1Events(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetEventsICS operation middleware
func (siw *ServerInterfaceWrapper) GetEventsICS(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetEventsICS(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/api/v1/add-event", wrapper.AddEvent)

	router.Get(options.BaseURL+"/api/v1/events", wrapper.GetApiV1Events)

	router.Get(options.BaseURL+"/api/v1/events.ics", wrapper.GetEventsICS)

	router.Get(options.BaseURL+"/api/v1/admin/events", wrapper.GetApiV1AdminEvents)

	router.Get(options.BaseURL+"/api/v1/admin/event-groups/search", wrapper.AdminSearchEventGroups)

	router.Get(options.BaseURL+"/api/v1/admin/event-groups/:eventGroupID", wrapper.AdminGetEventGroup)

	router.Post(options.BaseURL+"/api/v1/admin/duplicate-event-group", wrapper.AdminDuplicateEventGroup)

	router.Get(options.BaseURL+"/api/v1/admin/events/:eventID", wrapper.GetApiV1AdminEventsEventID)

	router.Put(options.BaseURL+"/api/v1/admin/events/:eventID/keyholders", wrapper.AdminSetEventKeyholders)

	router.Put(options.BaseURL+"/api/v1/admin/events/:eventID/dates", wrapper.AdminUpdateEventDates)

	router.Get(options.BaseURL+"/api/v1/admin/invoices/for-events", wrapper.AdminGetInvoicesForEvents)

	router.Get(options.BaseURL+"/api/v1/admin/invoices/by-id/:invoiceID", wrapper.AdminGetInvoiceByID)

	router.Post(options.BaseURL+"/api/v1/admin/send-invoice", wrapper.AdminSendInvoice)

	router.Post(options.BaseURL+"/api/v1/admin/invoices/by-id/:invoiceID/mark-as-paid", wrapper.AdminMarkInvoicePaid)

	router.Get(options.BaseURL+"/api/v1/admin/rates", wrapper.AdminGetRates)

	router.Post(options.BaseURL+"/api/v1/admin/rates", wrapper.AdminCreateRate)

	router.Put(options.BaseURL+"/api/v1/admin/rates/:rateID", wrapper.AdminUpdateRate)

	router.Post(options.BaseURL+"/api/v1/admin/events/:eventID/set-rate", wrapper.AdminEventSetRate)

	router.Post(options.BaseURL+"/api/v1/admin/events/:eventID/request-documents", wrapper.AdminEventRequestDocuments)

	router.Post(options.BaseURL+"/api/v1/admin/events/:eventID/cancel-event", wrapper.AdminEventCancel)

	router.Post(options.BaseURL+"/api/v1/admin/events/:eventID/approve-event", wrapper.AdminEventApprove)

	router.Post(options.BaseURL+"/api/v1/admin/add-events", wrapper.AdminAddEvents)

	router.Post(options.BaseURL+"/api/v1/admin/add-event-group", wrapper.AdminAddEventGroup)

	router.Get(options.BaseURL+"/api/v1/admin/contacts", wrapper.AdminListContacts)

	router.Get(options.BaseURL+"/api/v1/admin/keyholders", wrapper.AdminListKeyholders)

	router.Post(options.BaseURL+"/api/v1/admin/keyholders", wrapper.AdminCreateKeyholder)

	router.Put(options.BaseURL+"/api/v1/admin/keyholders/:keyholderID", wrapper.AdminUpdateKeyholder)

}

type AddEventRequestObject struct {
	Body *AddEventJSONRequestBody
}

type AddEventResponseObject interface {
	VisitAddEventResponse(ctx *fiber.Ctx) error
}

type AddEvent200Response struct {
}

func (response AddEvent200Response) VisitAddEventResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AddEvent409JSONResponse ErrorResponse

func (response AddEvent409JSONResponse) VisitAddEventResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type AddEvent422JSONResponse ErrorResponse

func (response AddEvent422JSONResponse) VisitAddEventResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AddEvent500JSONResponse ErrorResponse

func (response AddEvent500JSONResponse) VisitAddEventResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminAddEventGroupRequestObject struct {
	Body *AdminAddEventGroupJSONRequestBody
}

type AdminAddEventGroupResponseObject interface {
	VisitAdminAddEventGroupResponse(ctx *fiber.Ctx) error
}

type AdminAddEventGroup200Response struct {
}

func (response AdminAddEventGroup200Response) VisitAdminAddEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminAddEventGroup409JSONResponse ErrorResponse

func (response AdminAddEventGroup409JSONResponse) VisitAdminAddEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type AdminAddEventGroup422JSONResponse ErrorResponse

func (response AdminAddEventGroup422JSONResponse) VisitAdminAddEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AdminAddEventGroup500JSONResponse ErrorResponse

func (response AdminAddEventGroup500JSONResponse) VisitAdminAddEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminAddEventsRequestObject struct {
	Body *AdminAddEventsJSONRequestBody
}

type AdminAddEventsResponseObject interface {
	VisitAdminAddEventsResponse(ctx *fiber.Ctx) error
}

type AdminAddEvents200Response struct {
}

func (response AdminAddEvents200Response) VisitAdminAddEventsResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminAddEvents409JSONResponse ErrorResponse

func (response AdminAddEvents409JSONResponse) VisitAdminAddEventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type AdminAddEvents422JSONResponse ErrorResponse

func (response AdminAddEvents422JSONResponse) VisitAdminAddEventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AdminAddEvents500JSONResponse ErrorResponse

func (response AdminAddEvents500JSONResponse) VisitAdminAddEventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminListContactsRequestObject struct {
}

type AdminListContactsResponseObject interface {
	VisitAdminListContactsResponse(ctx *fiber.Ctx) error
}

type AdminListContacts200JSONResponse AdminContactList

func (response AdminListContacts200JSONResponse) VisitAdminListContactsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminListContacts500JSONResponse ErrorResponse

func (response AdminListContacts500JSONResponse) VisitAdminListContactsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminDuplicateEventGroupRequestObject struct {
	Body *AdminDuplicateEventGroupJSONRequestBody
}

type AdminDuplicateEventGroupResponseObject interface {
	VisitAdminDuplicateEventGroupResponse(ctx *fiber.Ctx) error
}

type AdminDuplicateEventGroup200Response struct {
}

func (response AdminDuplicateEventGroup200Response) VisitAdminDuplicateEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminDuplicateEventGroup404JSONResponse ErrorResponse

func (response AdminDuplicateEventGroup404JSONResponse) VisitAdminDuplicateEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminDuplicateEventGroup409JSONResponse ErrorResponse

func (response AdminDuplicateEventGroup409JSONResponse) VisitAdminDuplicateEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type AdminDuplicateEventGroup422JSONResponse ErrorResponse

func (response AdminDuplicateEventGroup422JSONResponse) VisitAdminDuplicateEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AdminDuplicateEventGroup500JSONResponse ErrorResponse

func (response AdminDuplicateEventGroup500JSONResponse) VisitAdminDuplicateEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminSearchEventGroupsRequestObject struct {
	Params AdminSearchEventGroupsParams
}

type AdminSearchEventGroupsResponseObject interface {
	VisitAdminSearchEventGroupsResponse(ctx *fiber.Ctx) error
}

type AdminSearchEventGroups200JSONResponse []AdminEventGroup

func (response AdminSearchEventGroups200JSONResponse) VisitAdminSearchEventGroupsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminSearchEventGroups400JSONResponse ErrorResponse

func (response AdminSearchEventGroups400JSONResponse) VisitAdminSearchEventGroupsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type AdminSearchEventGroups500JSONResponse ErrorResponse

func (response AdminSearchEventGroups500JSONResponse) VisitAdminSearchEventGroupsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminGetEventGroupRequestObject struct {
	EventGroupID string `json:"eventGroupID"`
}

type AdminGetEventGroupResponseObject interface {
	VisitAdminGetEventGroupResponse(ctx *fiber.Ctx) error
}

type AdminGetEventGroup200JSONResponse AdminEventGroupDetails

func (response AdminGetEventGroup200JSONResponse) VisitAdminGetEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminGetEventGroup404JSONResponse ErrorResponse

func (response AdminGetEventGroup404JSONResponse) VisitAdminGetEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminGetEventGroup500JSONResponse ErrorResponse

func (response AdminGetEventGroup500JSONResponse) VisitAdminGetEventGroupResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetApiV1AdminEventsRequestObject struct {
	Params GetApiV1AdminEventsParams
}

type GetApiV1AdminEventsResponseObject interface {
	VisitGetApiV1AdminEventsResponse(ctx *fiber.Ctx) error
}

type GetApiV1AdminEvents200JSONResponse AdminEventList

func (response GetApiV1AdminEvents200JSONResponse) VisitGetApiV1AdminEventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetApiV1AdminEvents400JSONResponse ErrorResponse

func (response GetApiV1AdminEvents400JSONResponse) VisitGetApiV1AdminEventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type GetApiV1AdminEvents500JSONResponse ErrorResponse

func (response GetApiV1AdminEvents500JSONResponse) VisitGetApiV1AdminEventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetApiV1AdminEventsEventIDRequestObject struct {
	EventID string `json:"eventID,omitempty"`
}

type GetApiV1AdminEventsEventIDResponseObject interface {
	VisitGetApiV1AdminEventsEventIDResponse(ctx *fiber.Ctx) error
}

type GetApiV1AdminEventsEventID200JSONResponse Event

func (response GetApiV1AdminEventsEventID200JSONResponse) VisitGetApiV1AdminEventsEventIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetApiV1AdminEventsEventID404JSONResponse ErrorResponse

func (response GetApiV1AdminEventsEventID404JSONResponse) VisitGetApiV1AdminEventsEventIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetApiV1AdminEventsEventID500JSONResponse ErrorResponse

func (response GetApiV1AdminEventsEventID500JSONResponse) VisitGetApiV1AdminEventsEventIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminEventApproveRequestObject struct {
	EventID string `json:"eventID,omitempty"`
}

type AdminEventApproveResponseObject interface {
	VisitAdminEventApproveResponse(ctx *fiber.Ctx) error
}

type AdminEventApprove200Response struct {
}

func (response AdminEventApprove200Response) VisitAdminEventApproveResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminEventApprove404JSONResponse ErrorResponse

func (response AdminEventApprove404JSONResponse) VisitAdminEventApproveResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminEventApprove500JSONResponse ErrorResponse

func (response AdminEventApprove500JSONResponse) VisitAdminEventApproveResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminEventCancelRequestObject struct {
	EventID string `json:"eventID,omitempty"`
}

type AdminEventCancelResponseObject interface {
	VisitAdminEventCancelResponse(ctx *fiber.Ctx) error
}

type AdminEventCancel200Response struct {
}

func (response AdminEventCancel200Response) VisitAdminEventCancelResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminEventCancel404JSONResponse ErrorResponse

func (response AdminEventCancel404JSONResponse) VisitAdminEventCancelResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminEventCancel500JSONResponse ErrorResponse

func (response AdminEventCancel500JSONResponse) VisitAdminEventCancelResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminUpdateEventDatesRequestObject struct {
	EventID string `json:"eventID"`
	Body    *AdminUpdateEventDatesJSONRequestBody
}

type AdminUpdateEventDatesResponseObject interface {
	VisitAdminUpdateEventDatesResponse(ctx *fiber.Ctx) error
}

type AdminUpdateEventDates200Response struct {
}

func (response AdminUpdateEventDates200Response) VisitAdminUpdateEventDatesResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminUpdateEventDates404JSONResponse ErrorResponse

func (response AdminUpdateEventDates404JSONResponse) VisitAdminUpdateEventDatesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminUpdateEventDates409JSONResponse ErrorResponse

func (response AdminUpdateEventDates409JSONResponse) VisitAdminUpdateEventDatesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type AdminUpdateEventDates422JSONResponse ErrorResponse

func (response AdminUpdateEventDates422JSONResponse) VisitAdminUpdateEventDatesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AdminUpdateEventDates500JSONResponse ErrorResponse

func (response AdminUpdateEventDates500JSONResponse) VisitAdminUpdateEventDatesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminSetEventKeyholdersRequestObject struct {
	EventID string `json:"eventID"`
	Body    *AdminSetEventKeyholdersJSONRequestBody
}

type AdminSetEventKeyholdersResponseObject interface {
	VisitAdminSetEventKeyholdersResponse(ctx *fiber.Ctx) error
}

type AdminSetEventKeyholders200Response struct {
}

func (response AdminSetEventKeyholders200Response) VisitAdminSetEventKeyholdersResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminSetEventKeyholders404JSONResponse ErrorResponse

func (response AdminSetEventKeyholders404JSONResponse) VisitAdminSetEventKeyholdersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminSetEventKeyholders422JSONResponse ErrorResponse

func (response AdminSetEventKeyholders422JSONResponse) VisitAdminSetEventKeyholdersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AdminSetEventKeyholders500JSONResponse ErrorResponse

func (response AdminSetEventKeyholders500JSONResponse) VisitAdminSetEventKeyholdersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminEventRequestDocumentsRequestObject struct {
	EventID string `json:"eventID,omitempty"`
	Body    *AdminEventRequestDocumentsJSONRequestBody
}

type AdminEventRequestDocumentsResponseObject interface {
	VisitAdminEventRequestDocumentsResponse(ctx *fiber.Ctx) error
}

type AdminEventRequestDocuments200Response struct {
}

func (response AdminEventRequestDocuments200Response) VisitAdminEventRequestDocumentsResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminEventRequestDocuments404JSONResponse ErrorResponse

func (response AdminEventRequestDocuments404JSONResponse) VisitAdminEventRequestDocumentsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminEventRequestDocuments500JSONResponse ErrorResponse

func (response AdminEventRequestDocuments500JSONResponse) VisitAdminEventRequestDocumentsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminEventSetRateRequestObject struct {
	EventID string `json:"eventID,omitempty"`
	Body    *AdminEventSetRateJSONRequestBody
}

type AdminEventSetRateResponseObject interface {
	VisitAdminEventSetRateResponse(ctx *fiber.Ctx) error
}

type AdminEventSetRate200Response struct {
}

func (response AdminEventSetRate200Response) VisitAdminEventSetRateResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminEventSetRate404JSONResponse ErrorResponse

func (response AdminEventSetRate404JSONResponse) VisitAdminEventSetRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminEventSetRate500JSONResponse ErrorResponse

func (response AdminEventSetRate500JSONResponse) VisitAdminEventSetRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminGetInvoiceByIDRequestObject struct {
	InvoiceID string `json:"invoiceID,omitempty"`
}

type AdminGetInvoiceByIDResponseObject interface {
	VisitAdminGetInvoiceByIDResponse(ctx *fiber.Ctx) error
}

type AdminGetInvoiceByID200JSONResponse Invoice

func (response AdminGetInvoiceByID200JSONResponse) VisitAdminGetInvoiceByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminGetInvoiceByID404JSONResponse ErrorResponse

func (response AdminGetInvoiceByID404JSONResponse) VisitAdminGetInvoiceByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminGetInvoiceByID500JSONResponse ErrorResponse

func (response AdminGetInvoiceByID500JSONResponse) VisitAdminGetInvoiceByIDResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminMarkInvoicePaidRequestObject struct {
	InvoiceID string `json:"invoiceID,omitempty"`
}

type AdminMarkInvoicePaidResponseObject interface {
	VisitAdminMarkInvoicePaidResponse(ctx *fiber.Ctx) error
}

type AdminMarkInvoicePaid200Response struct {
}

func (response AdminMarkInvoicePaid200Response) VisitAdminMarkInvoicePaidResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminMarkInvoicePaid404JSONResponse ErrorResponse

func (response AdminMarkInvoicePaid404JSONResponse) VisitAdminMarkInvoicePaidResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminMarkInvoicePaid500JSONResponse ErrorResponse

func (response AdminMarkInvoicePaid500JSONResponse) VisitAdminMarkInvoicePaidResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminGetInvoicesForEventsRequestObject struct {
	Params AdminGetInvoicesForEventsParams
}

type AdminGetInvoicesForEventsResponseObject interface {
	VisitAdminGetInvoicesForEventsResponse(ctx *fiber.Ctx) error
}

type AdminGetInvoicesForEvents200JSONResponse InvoicePreparations

func (response AdminGetInvoicesForEvents200JSONResponse) VisitAdminGetInvoicesForEventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminGetInvoicesForEvents404JSONResponse ErrorResponse

func (response AdminGetInvoicesForEvents404JSONResponse) VisitAdminGetInvoicesForEventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminGetInvoicesForEvents500JSONResponse ErrorResponse

func (response AdminGetInvoicesForEvents500JSONResponse) VisitAdminGetInvoicesForEventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminListKeyholdersRequestObject struct {
}

type AdminListKeyholdersResponseObject interface {
	VisitAdminListKeyholdersResponse(ctx *fiber.Ctx) error
}

type AdminListKeyholders200JSONResponse KeyholderList

func (response AdminListKeyholders200JSONResponse) VisitAdminListKeyholdersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminListKeyholders500JSONResponse ErrorResponse

func (response AdminListKeyholders500JSONResponse) VisitAdminListKeyholdersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminCreateKeyholderRequestObject struct {
	Body *AdminCreateKeyholderJSONRequestBody
}

type AdminCreateKeyholderResponseObject interface {
	VisitAdminCreateKeyholderResponse(ctx *fiber.Ctx) error
}

type AdminCreateKeyholder200JSONResponse Keyholder

func (response AdminCreateKeyholder200JSONResponse) VisitAdminCreateKeyholderResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminCreateKeyholder409JSONResponse ErrorResponse

func (response AdminCreateKeyholder409JSONResponse) VisitAdminCreateKeyholderResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type AdminCreateKeyholder422JSONResponse ErrorResponse

func (response AdminCreateKeyholder422JSONResponse) VisitAdminCreateKeyholderResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AdminCreateKeyholder500JSONResponse ErrorResponse

func (response AdminCreateKeyholder500JSONResponse) VisitAdminCreateKeyholderResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminUpdateKeyholderRequestObject struct {
	KeyholderID openapi_types.UUID `json:"keyholderID"`
	Body        *AdminUpdateKeyholderJSONRequestBody
}

type AdminUpdateKeyholderResponseObject interface {
	VisitAdminUpdateKeyholderResponse(ctx *fiber.Ctx) error
}

type AdminUpdateKeyholder200JSONResponse Keyholder

func (response AdminUpdateKeyholder200JSONResponse) VisitAdminUpdateKeyholderResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminUpdateKeyholder404JSONResponse ErrorResponse

func (response AdminUpdateKeyholder404JSONResponse) VisitAdminUpdateKeyholderResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminUpdateKeyholder409JSONResponse ErrorResponse

func (response AdminUpdateKeyholder409JSONResponse) VisitAdminUpdateKeyholderResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type AdminUpdateKeyholder422JSONResponse ErrorResponse

func (response AdminUpdateKeyholder422JSONResponse) VisitAdminUpdateKeyholderResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AdminUpdateKeyholder500JSONResponse ErrorResponse

func (response AdminUpdateKeyholder500JSONResponse) VisitAdminUpdateKeyholderResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminGetRatesRequestObject struct {
}

type AdminGetRatesResponseObject interface {
	VisitAdminGetRatesResponse(ctx *fiber.Ctx) error
}

type AdminGetRates200JSONResponse RatesList

func (response AdminGetRates200JSONResponse) VisitAdminGetRatesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminGetRates500JSONResponse ErrorResponse

func (response AdminGetRates500JSONResponse) VisitAdminGetRatesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminCreateRateRequestObject struct {
	Body *AdminCreateRateJSONRequestBody
}

type AdminCreateRateResponseObject interface {
	VisitAdminCreateRateResponse(ctx *fiber.Ctx) error
}

type AdminCreateRate200JSONResponse Rate

func (response AdminCreateRate200JSONResponse) VisitAdminCreateRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminCreateRate409JSONResponse ErrorResponse

func (response AdminCreateRate409JSONResponse) VisitAdminCreateRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type AdminCreateRate422JSONResponse ErrorResponse

func (response AdminCreateRate422JSONResponse) VisitAdminCreateRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AdminCreateRate500JSONResponse ErrorResponse

func (response AdminCreateRate500JSONResponse) VisitAdminCreateRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminUpdateRateRequestObject struct {
	RateID string `json:"rateID"`
	Body   *AdminUpdateRateJSONRequestBody
}

type AdminUpdateRateResponseObject interface {
	VisitAdminUpdateRateResponse(ctx *fiber.Ctx) error
}

type AdminUpdateRate200JSONResponse Rate

func (response AdminUpdateRate200JSONResponse) VisitAdminUpdateRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type AdminUpdateRate404JSONResponse ErrorResponse

func (response AdminUpdateRate404JSONResponse) VisitAdminUpdateRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminUpdateRate422JSONResponse ErrorResponse

func (response AdminUpdateRate422JSONResponse) VisitAdminUpdateRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type AdminUpdateRate500JSONResponse ErrorResponse

func (response AdminUpdateRate500JSONResponse) VisitAdminUpdateRateResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type AdminSendInvoiceRequestObject struct {
	Body *AdminSendInvoiceJSONRequestBody
}

type AdminSendInvoiceResponseObject interface {
	VisitAdminSendInvoiceResponse(ctx *fiber.Ctx) error
}

type AdminSendInvoice200Response struct {
}

func (response AdminSendInvoice200Response) VisitAdminSendInvoiceResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type AdminSendInvoice404JSONResponse ErrorResponse

func (response AdminSendInvoice404JSONResponse) VisitAdminSendInvoiceResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type AdminSendInvoice500JSONResponse ErrorResponse

func (response AdminSendInvoice500JSONResponse) VisitAdminSendInvoiceResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetApiV1EventsRequestObject struct {
	Params GetApiV1EventsParams
}

type GetApiV1EventsResponseObject interface {
	VisitGetApiV1EventsResponse(ctx *fiber.Ctx) error
}

type GetApiV1Events200JSONResponse EventList

func (response GetApiV1Events200JSONResponse) VisitGetApiV1EventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetApiV1Events400JSONResponse ErrorResponse

func (response GetApiV1Events400JSONResponse) VisitGetApiV1EventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type GetApiV1Events500JSONResponse ErrorResponse

func (response GetApiV1Events500JSONResponse) VisitGetApiV1EventsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetEventsICSRequestObject struct {
}

type GetEventsICSResponseObject interface {
	VisitGetEventsICSResponse(ctx *fiber.Ctx) error
}

type GetEventsICS200TextcalendarResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetEventsICS200TextcalendarResponse) VisitGetEventsICSResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/calendar")
	if response.ContentLength != 0 {
		ctx.Response().Header.Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.Status(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.Response().BodyWriter(), response.Body)
	return err
}

type GetEventsICS400JSONResponse ErrorResponse

func (response GetEventsICS400JSONResponse) VisitGetEventsICSResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type GetEventsICS500JSONResponse ErrorResponse

func (response GetEventsICS500JSONResponse) VisitGetEventsICSResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// AddEvent Add an event
	// (POST /api/v1/add-event)
	AddEvent(ctx context.Context, request AddEventRequestObject) (AddEventResponseObject, error)
	// AdminAddEventGroup Add an event group
	// (POST /api/v1/admin/add-event-group)
	AdminAddEventGroup(ctx context.Context, request AdminAddEventGroupRequestObject) (AdminAddEventGroupResponseObject, error)
	// AdminAddEvents Add events
	// (POST /api/v1/admin/add-events)
	AdminAddEvents(ctx context.Context, request AdminAddEventsRequestObject) (AdminAddEventsResponseObject, error)
	// AdminListContacts List contacts
	// (GET /api/v1/admin/contacts)
	AdminListContacts(ctx context.Context, request AdminListContactsRequestObject) (AdminListContactsResponseObject, error)
	// AdminDuplicateEventGroup Duplicate an event group
	// (POST /api/v1/admin/duplicate-event-group)
	AdminDuplicateEventGroup(ctx context.Context, request AdminDuplicateEventGroupRequestObject) (AdminDuplicateEventGroupResponseObject, error)
	// AdminSearchEventGroups Search event groups by title
	// (GET /api/v1/admin/event-groups/search)
	AdminSearchEventGroups(ctx context.Context, request AdminSearchEventGroupsRequestObject) (AdminSearchEventGroupsResponseObject, error)
	// AdminGetEventGroup Get an event group for duplication
	// (GET /api/v1/admin/event-groups/{eventGroupID})
	AdminGetEventGroup(ctx context.Context, request AdminGetEventGroupRequestObject) (AdminGetEventGroupResponseObject, error)

	// (GET /api/v1/admin/events)
	GetApiV1AdminEvents(ctx context.Context, request GetApiV1AdminEventsRequestObject) (GetApiV1AdminEventsResponseObject, error)

	// (GET /api/v1/admin/events/{eventID})
	GetApiV1AdminEventsEventID(ctx context.Context, request GetApiV1AdminEventsEventIDRequestObject) (GetApiV1AdminEventsEventIDResponseObject, error)

	// (POST /api/v1/admin/events/{eventID}/approve-event)
	AdminEventApprove(ctx context.Context, request AdminEventApproveRequestObject) (AdminEventApproveResponseObject, error)

	// (POST /api/v1/admin/events/{eventID}/cancel-event)
	AdminEventCancel(ctx context.Context, request AdminEventCancelRequestObject) (AdminEventCancelResponseObject, error)
	// AdminUpdateEventDates Update event dates and times
	// (PUT /api/v1/admin/events/{eventID}/dates)
	AdminUpdateEventDates(ctx context.Context, request AdminUpdateEventDatesRequestObject) (AdminUpdateEventDatesResponseObject, error)
	// AdminSetEventKeyholders Set event keyholders
	// (PUT /api/v1/admin/events/{eventID}/keyholders)
	AdminSetEventKeyholders(ctx context.Context, request AdminSetEventKeyholdersRequestObject) (AdminSetEventKeyholdersResponseObject, error)

	// (POST /api/v1/admin/events/{eventID}/request-documents)
	AdminEventRequestDocuments(ctx context.Context, request AdminEventRequestDocumentsRequestObject) (AdminEventRequestDocumentsResponseObject, error)

	// (POST /api/v1/admin/events/{eventID}/set-rate)
	AdminEventSetRate(ctx context.Context, request AdminEventSetRateRequestObject) (AdminEventSetRateResponseObject, error)

	// (GET /api/v1/admin/invoices/by-id/{invoiceID})
	AdminGetInvoiceByID(ctx context.Context, request AdminGetInvoiceByIDRequestObject) (AdminGetInvoiceByIDResponseObject, error)

	// (POST /api/v1/admin/invoices/by-id/{invoiceID}/mark-as-paid)
	AdminMarkInvoicePaid(ctx context.Context, request AdminMarkInvoicePaidRequestObject) (AdminMarkInvoicePaidResponseObject, error)

	// (GET /api/v1/admin/invoices/for-events)
	AdminGetInvoicesForEvents(ctx context.Context, request AdminGetInvoicesForEventsRequestObject) (AdminGetInvoicesForEventsResponseObject, error)
	// AdminListKeyholders List keyholders
	// (GET /api/v1/admin/keyholders)
	AdminListKeyholders(ctx context.Context, request AdminListKeyholdersRequestObject) (AdminListKeyholdersResponseObject, error)
	// AdminCreateKeyholder Create a keyholder
	// (POST /api/v1/admin/keyholders)
	AdminCreateKeyholder(ctx context.Context, request AdminCreateKeyholderRequestObject) (AdminCreateKeyholderResponseObject, error)
	// AdminUpdateKeyholder Update a keyholder
	// (PUT /api/v1/admin/keyholders/{keyholderID})
	AdminUpdateKeyholder(ctx context.Context, request AdminUpdateKeyholderRequestObject) (AdminUpdateKeyholderResponseObject, error)

	// (GET /api/v1/admin/rates)
	AdminGetRates(ctx context.Context, request AdminGetRatesRequestObject) (AdminGetRatesResponseObject, error)

	// (POST /api/v1/admin/rates)
	AdminCreateRate(ctx context.Context, request AdminCreateRateRequestObject) (AdminCreateRateResponseObject, error)

	// (PUT /api/v1/admin/rates/{rateID})
	AdminUpdateRate(ctx context.Context, request AdminUpdateRateRequestObject) (AdminUpdateRateResponseObject, error)

	// (POST /api/v1/admin/send-invoice)
	AdminSendInvoice(ctx context.Context, request AdminSendInvoiceRequestObject) (AdminSendInvoiceResponseObject, error)

	// (GET /api/v1/events)
	GetApiV1Events(ctx context.Context, request GetApiV1EventsRequestObject) (GetApiV1EventsResponseObject, error)

	// (GET /api/v1/events.ics)
	GetEventsICS(ctx context.Context, request GetEventsICSRequestObject) (GetEventsICSResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// AddEvent operation middleware
func (sh *strictHandler) AddEvent(ctx *fiber.Ctx) error {
	var request AddEventRequestObject

	var body AddEventJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AddEvent(ctx.UserContext(), request.(AddEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AddEventResponseObject); ok {
		if err := validResponse.VisitAddEventResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminAddEventGroup operation middleware
func (sh *strictHandler) AdminAddEventGroup(ctx *fiber.Ctx) error {
	var request AdminAddEventGroupRequestObject

	var body AdminAddEventGroupJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminAddEventGroup(ctx.UserContext(), request.(AdminAddEventGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminAddEventGroup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminAddEventGroupResponseObject); ok {
		if err := validResponse.VisitAdminAddEventGroupResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminAddEvents operation middleware
func (sh *strictHandler) AdminAddEvents(ctx *fiber.Ctx) error {
	var request AdminAddEventsRequestObject

	var body AdminAddEventsJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminAddEvents(ctx.UserContext(), request.(AdminAddEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminAddEvents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminAddEventsResponseObject); ok {
		if err := validResponse.VisitAdminAddEventsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminListContacts operation middleware
func (sh *strictHandler) AdminListContacts(ctx *fiber.Ctx) error {
	var request AdminListContactsRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminListContacts(ctx.UserContext(), request.(AdminListContactsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminListContacts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminListContactsResponseObject); ok {
		if err := validResponse.VisitAdminListContactsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminDuplicateEventGroup operation middleware
func (sh *strictHandler) AdminDuplicateEventGroup(ctx *fiber.Ctx) error {
	var request AdminDuplicateEventGroupRequestObject

	var body AdminDuplicateEventGroupJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminDuplicateEventGroup(ctx.UserContext(), request.(AdminDuplicateEventGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminDuplicateEventGroup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminDuplicateEventGroupResponseObject); ok {
		if err := validResponse.VisitAdminDuplicateEventGroupResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminSearchEventGroups operation middleware
func (sh *strictHandler) AdminSearchEventGroups(ctx *fiber.Ctx, params AdminSearchEventGroupsParams) error {
	var request AdminSearchEventGroupsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminSearchEventGroups(ctx.UserContext(), request.(AdminSearchEventGroupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminSearchEventGroups")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminSearchEventGroupsResponseObject); ok {
		if err := validResponse.VisitAdminSearchEventGroupsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminGetEventGroup operation middleware
func (sh *strictHandler) AdminGetEventGroup(ctx *fiber.Ctx, eventGroupID string) error {
	var request AdminGetEventGroupRequestObject

	request.EventGroupID = eventGroupID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminGetEventGroup(ctx.UserContext(), request.(AdminGetEventGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminGetEventGroup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminGetEventGroupResponseObject); ok {
		if err := validResponse.VisitAdminGetEventGroupResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetApiV1AdminEvents operation middleware
func (sh *strictHandler) GetApiV1AdminEvents(ctx *fiber.Ctx, params GetApiV1AdminEventsParams) error {
	var request GetApiV1AdminEventsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AdminEvents(ctx.UserContext(), request.(GetApiV1AdminEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AdminEvents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetApiV1AdminEventsResponseObject); ok {
		if err := validResponse.VisitGetApiV1AdminEventsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetApiV1AdminEventsEventID operation middleware
func (sh *strictHandler) GetApiV1AdminEventsEventID(ctx *fiber.Ctx, eventID string) error {
	var request GetApiV1AdminEventsEventIDRequestObject

	request.EventID = eventID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AdminEventsEventID(ctx.UserContext(), request.(GetApiV1AdminEventsEventIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AdminEventsEventID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetApiV1AdminEventsEventIDResponseObject); ok {
		if err := validResponse.VisitGetApiV1AdminEventsEventIDResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminEventApprove operation middleware
func (sh *strictHandler) AdminEventApprove(ctx *fiber.Ctx, eventID string) error {
	var request AdminEventApproveRequestObject

	request.EventID = eventID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminEventApprove(ctx.UserContext(), request.(AdminEventApproveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminEventApprove")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminEventApproveResponseObject); ok {
		if err := validResponse.VisitAdminEventApproveResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminEventCancel operation middleware
func (sh *strictHandler) AdminEventCancel(ctx *fiber.Ctx, eventID string) error {
	var request AdminEventCancelRequestObject

	request.EventID = eventID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminEventCancel(ctx.UserContext(), request.(AdminEventCancelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminEventCancel")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminEventCancelResponseObject); ok {
		if err := validResponse.VisitAdminEventCancelResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminUpdateEventDates operation middleware
func (sh *strictHandler) AdminUpdateEventDates(ctx *fiber.Ctx, eventID string) error {
	var request AdminUpdateEventDatesRequestObject

	request.EventID = eventID

	var body AdminUpdateEventDatesJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminUpdateEventDates(ctx.UserContext(), request.(AdminUpdateEventDatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminUpdateEventDates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminUpdateEventDatesResponseObject); ok {
		if err := validResponse.VisitAdminUpdateEventDatesResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminSetEventKeyholders operation middleware
func (sh *strictHandler) AdminSetEventKeyholders(ctx *fiber.Ctx, eventID string) error {
	var request AdminSetEventKeyholdersRequestObject

	request.EventID = eventID

	var body AdminSetEventKeyholdersJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminSetEventKeyholders(ctx.UserContext(), request.(AdminSetEventKeyholdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminSetEventKeyholders")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminSetEventKeyholdersResponseObject); ok {
		if err := validResponse.VisitAdminSetEventKeyholdersResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminEventRequestDocuments operation middleware
func (sh *strictHandler) AdminEventRequestDocuments(ctx *fiber.Ctx, eventID string) error {
	var request AdminEventRequestDocumentsRequestObject

	request.EventID = eventID

	var body AdminEventRequestDocumentsJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminEventRequestDocuments(ctx.UserContext(), request.(AdminEventRequestDocumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminEventRequestDocuments")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminEventRequestDocumentsResponseObject); ok {
		if err := validResponse.VisitAdminEventRequestDocumentsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminEventSetRate operation middleware
func (sh *strictHandler) AdminEventSetRate(ctx *fiber.Ctx, eventID string) error {
	var request AdminEventSetRateRequestObject

	request.EventID = eventID

	var body AdminEventSetRateJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminEventSetRate(ctx.UserContext(), request.(AdminEventSetRateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminEventSetRate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminEventSetRateResponseObject); ok {
		if err := validResponse.VisitAdminEventSetRateResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminGetInvoiceByID operation middleware
func (sh *strictHandler) AdminGetInvoiceByID(ctx *fiber.Ctx, invoiceID string) error {
	var request AdminGetInvoiceByIDRequestObject

	request.InvoiceID = invoiceID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminGetInvoiceByID(ctx.UserContext(), request.(AdminGetInvoiceByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminGetInvoiceByID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminGetInvoiceByIDResponseObject); ok {
		if err := validResponse.VisitAdminGetInvoiceByIDResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminMarkInvoicePaid operation middleware
func (sh *strictHandler) AdminMarkInvoicePaid(ctx *fiber.Ctx, invoiceID string) error {
	var request AdminMarkInvoicePaidRequestObject

	request.InvoiceID = invoiceID

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminMarkInvoicePaid(ctx.UserContext(), request.(AdminMarkInvoicePaidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminMarkInvoicePaid")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminMarkInvoicePaidResponseObject); ok {
		if err := validResponse.VisitAdminMarkInvoicePaidResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminGetInvoicesForEvents operation middleware
func (sh *strictHandler) AdminGetInvoicesForEvents(ctx *fiber.Ctx, params AdminGetInvoicesForEventsParams) error {
	var request AdminGetInvoicesForEventsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminGetInvoicesForEvents(ctx.UserContext(), request.(AdminGetInvoicesForEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminGetInvoicesForEvents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminGetInvoicesForEventsResponseObject); ok {
		if err := validResponse.VisitAdminGetInvoicesForEventsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminListKeyholders operation middleware
func (sh *strictHandler) AdminListKeyholders(ctx *fiber.Ctx) error {
	var request AdminListKeyholdersRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminListKeyholders(ctx.UserContext(), request.(AdminListKeyholdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminListKeyholders")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminListKeyholdersResponseObject); ok {
		if err := validResponse.VisitAdminListKeyholdersResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminCreateKeyholder operation middleware
func (sh *strictHandler) AdminCreateKeyholder(ctx *fiber.Ctx) error {
	var request AdminCreateKeyholderRequestObject

	var body AdminCreateKeyholderJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminCreateKeyholder(ctx.UserContext(), request.(AdminCreateKeyholderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminCreateKeyholder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminCreateKeyholderResponseObject); ok {
		if err := validResponse.VisitAdminCreateKeyholderResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminUpdateKeyholder operation middleware
func (sh *strictHandler) AdminUpdateKeyholder(ctx *fiber.Ctx, keyholderID openapi_types.UUID) error {
	var request AdminUpdateKeyholderRequestObject

	request.KeyholderID = keyholderID

	var body AdminUpdateKeyholderJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminUpdateKeyholder(ctx.UserContext(), request.(AdminUpdateKeyholderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminUpdateKeyholder")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminUpdateKeyholderResponseObject); ok {
		if err := validResponse.VisitAdminUpdateKeyholderResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminGetRates operation middleware
func (sh *strictHandler) AdminGetRates(ctx *fiber.Ctx) error {
	var request AdminGetRatesRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminGetRates(ctx.UserContext(), request.(AdminGetRatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminGetRates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminGetRatesResponseObject); ok {
		if err := validResponse.VisitAdminGetRatesResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminCreateRate operation middleware
func (sh *strictHandler) AdminCreateRate(ctx *fiber.Ctx) error {
	var request AdminCreateRateRequestObject

	var body AdminCreateRateJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminCreateRate(ctx.UserContext(), request.(AdminCreateRateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminCreateRate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminCreateRateResponseObject); ok {
		if err := validResponse.VisitAdminCreateRateResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminUpdateRate operation middleware
func (sh *strictHandler) AdminUpdateRate(ctx *fiber.Ctx, rateID string) error {
	var request AdminUpdateRateRequestObject

	request.RateID = rateID

	var body AdminUpdateRateJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminUpdateRate(ctx.UserContext(), request.(AdminUpdateRateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminUpdateRate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminUpdateRateResponseObject); ok {
		if err := validResponse.VisitAdminUpdateRateResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminSendInvoice operation middleware
func (sh *strictHandler) AdminSendInvoice(ctx *fiber.Ctx) error {
	var request AdminSendInvoiceRequestObject

	var body AdminSendInvoiceJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.AdminSendInvoice(ctx.UserContext(), request.(AdminSendInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminSendInvoice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminSendInvoiceResponseObject); ok {
		if err := validResponse.VisitAdminSendInvoiceResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetApiV1Events operation middleware
func (sh *strictHandler) GetApiV1Events(ctx *fiber.Ctx, params GetApiV1EventsParams) error {
	var request GetApiV1EventsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Events(ctx.UserContext(), request.(GetApiV1EventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Events")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetApiV1EventsResponseObject); ok {
		if err := validResponse.VisitGetApiV1EventsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEventsICS operation middleware
func (sh *strictHandler) GetEventsICS(ctx *fiber.Ctx) error {
	var request GetEventsICSRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetEventsICS(ctx.UserContext(), request.(GetEventsICSRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEventsICS")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetEventsICSResponseObject); ok {
		if err := validResponse.VisitGetEventsICSResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F3rU9w4Ev9XVL6rui8DQ5K9D8c3Ftgct9mEYrJ7VZdKUcLumdFiS15JhkxR/O9XevkpP2aYF8l8Ayy3",
	"Wq1fP9TdMk9ByJKUUaBSBKdPgQjnkGD941mUEHrOqMShVL+nnKXAJQH9FBJMYvXDlPEEy+DU/mUUyEUK",
	"wWkgJCd0FjyPAooTUCNrD55HAYe/MsIhCk6/mFEjS+VrTobd/QmhVGTK/HwgQvNEJCSanb9zmAanwd/G",
	"xXLGdi3jykKec8qYc7zICV9kaUxCLOHyAah8z1mWehatnt3O1MNbEnnWNAoIFRLTEMRg9vSEV/Y1RSIh",
	"9Mq8+KbJ7D0s5iyOgFdkn2Uk8omeYzlA9LVl2dfKc5XX1bo3XZKbcpZUOI6wBEn0ljdl2CbaB0aWkeyV",
	"eeEGpr5tb4HlKJBsIKc1MWrRWRjr9WpSA8R1ARKTWDSlFnZq3y2OIg5CbEoLc/q+JUQFz0P3rwLd6npI",
	"VFlEG5yHraHYBx/jrdueZncxCePF7QMR5C4uD7pjLAZMOzRqFCiI3HJMZzWA9uhBmw5INmBYbeHdoKvi",
	"vwO7bms9IhnlkPQaibIMunHvDLjHvmqVEMtZ95Lp8Wi6JrukQe6VmCU6qjDduuiP8NhlHl+ror/c2b3M",
	"v21Gmf2iKtSiWLZXRTyK4fa3Fx+vywlo6DcZ2xVkrqgPNDSLY6whIHkGow6/9CmTKxFYCoURTHEWyxqx",
	"IR5GSCwzsX68Wrp25uY++wxfD6bP9xez5xywhF/dnv/MokWTzXtYfMySO2OFEkJJkiXlcJxQCTPgZfYS",
	"Qj8Ancl5eVw3s8Us7YzeYAl+HiNM4sWNBUvO40lOiRrS2oSLkJNUEkZ7OR0Fc5bxgYRJNIAeoUQSHF8o",
	"dq+BExaJfqmWXxrESgp8AkLYJXbZk+t85DUnodNU8+NvLIK+9xU716XhSjMLeg1OW6yH49wXh5X3q8pa",
	"ZXdq81Zk4APUBREhy6j8jK0pwlFE1CQ4vq4gq2v1FSI37DF47ptJDWqA17zyFABVYvoSTGNctiQFeh5w",
	"nJXVv0Vu+qkb7Vv8JeeM34BIGRXQ5AfU49sEhMCzISfmynDvfH7XiIUgMwowzPSVXH/jWZeTXSI5U0Sv",
	"VxdeWnt4cq85/C5CuZ0/04JPbGRfd/krkGh1+sqLtsiy8OC9Ac/EDF0mHTEKOoLdQee94gBZigp8Zz8H",
	"J7vWVgVozWx0oXcpxK039lo19dMpyQYnreLKo9yX5c9WXUV3/qDv3D5cuxWRpQ7ZrexMcoVyjiTlTIlZ",
	"ObVgFOBHTCShMxSxMEvsgR2nahAoDQiVtOMYIq/vsVao80i2jIUdaPWKRMEkSxLMV8lhlEmVqNQtaZu9",
	"dlMsM5fKWfvmSDGJBuJRbf4UOFgVaDwV1qcOIjXM2Frmnbn1mcmCp5JVLGyhkZEPouVN8JjAejg2OOxa",
	"l1vudGGemMs8uICpjs77I20dpW7c7Q3KwtdPuaOa+BtL69vPin5upNyxw/qEz3p8p2vUVstj4IX0KkDt",
	"KD1snTUeNfEqqQ4GrzmkmGM34wsckR38sU3mVUflf7yaB/K5hcQetZ3jJjQiDyTKtN/WtUivT3aIqWyE",
	"CQaQeoamjKOCFkoL8SHGkV7EkSZfDDe/lkYed9VS+y1ebb8Tc3IvPEZ5I3K0doQ6TSR4Iuq09nSZTSpR",
	"7g3JKvN0cKvObi11vmas/h2GCB2iaUatHBOhA1Itib649Nf2QioOJXloqXYMLLJuOPdZttDFVCPHuU9s",
	"vhP4LkvIOT9LtaHkb/msYXEk2q6f3c+MRGcewrcjrnzmUYhoDoI8gPCxoBQtleEcf2b34HfoIebXmN+r",
	"3/wE1A+Ezs5odIGTavKwPKxw1F2CLnUp5bW13o1xSRaTxn7A4eKaxSRc+DmRwBPxafpvwofsSr3YU5NY",
	"fcYqeZ90KhIdlbbHt63NVP1QZSve/EyMxiX4m+2qettUv9pwT5yVUdlvD1NfAaA7cW1e8S3elT3WVPVp",
	"JpDr588GB0tXgg61n32t/dQZL8UehqqyuuQbRI5IheIoSLJYkgu88MYjirhYyhe6zEBdD2/grwyEvHDZ",
	"On/lM2RiPp/MAWSLVY/uxLkaPtUdnf4xU8aiCZ6CbLGTJmv7geA7EpO2QZyI+zOhtsIFJT32tE61wkeD",
	"3qiy1Ma6fBs9ARrZMLNNeCvnLjuOhNXjmMICYlNkjmVXFwLJOZZIzolAthaEcJrGBASS7DgoZRwbczRS",
	"lkvlJmvi8OcoG+fz/tSej+76sghart4a0mqphAmY4DIPQUVr28MuO2lqiytzU6Pdssj2ZolhnV68Tat+",
	"TyPXGn6hjJ1/kj0o0hhGe7pbug6J2+586Tz4mdXsdwvMIcIZHuFsJLjRHIYZJ3IxUYtw576E0FucqS1+",
	"Cu4Ac+C/OGX7z38/q0n06ODUPi00by5lGjw/642asqZ7+/zp4lMwCmISgm0mMaoQvP/4OzqbToEz9P76",
	"A3p3fBKMgozHlqY4HY8fHx+PZzQ7Znw2tgTEGM/S+Ojd8ckx0OO5TGLTTy6VWIOfGVNnJTRZCAkJOru+",
	"Umdh4AYMwZvjk+MTNZ6lQHFKgtNAEXqnc0lyrmUxxikZP7wZ4yg6Klo2rXOqLu0sihBGFB5NphRJhuQc",
	"UIhjoBFWMlL6p7N/V5EZf2mPiNzEbk5TlRe1U2lXH+qXxn8Kg2GDtz405ud6vRu+nK9k6A4QjiKIgjLY",
	"FBw1+kzHj5bD25OT5oonWRiCENMsjheWzvMo+OnkX2tbRLX1yLOSM8rkHGxyGsE3IqRAjJp4KbKh8k9v",
	"326Poz9wTCJNGcG3EFKXGf7nycn2mJiwBORcYf9RyeWRM+tQhCtJGbhS5LIUEs9EEWUHX9XgAvwJoYUK",
	"mBpAWRHqwE4Ideg2EfBmIO65HvD8/PxaofyJgiqzJIwDChmdxiSUwkD6AOIqiK3PCk6/VL3Vl6/PX9sw",
	"bkpVQQeuRbdtzy27GGDaSxogtoF+0WrmxXdh5w/KsRHlAIedulLYg7zGxAzajLxKVpy7kX4krQ/q5fvL",
	"HoHkfLy+ndA5n7CQo/PF+h2fK47cjeslHLLvlvYGDZNvulWd82Vhv1G+9AiJklkyBumnbe56xkMouxYU",
	"MRCIMlkyS7sykeqlKIsPtnJNGpqjuR5ODFDWkoqKsQDMw3m3VZ3oMZelu7HqQMpxAhK40LzWTB8WcESo",
	"ACqISgihFHOVJKm07OhDsYoFDAuqeycYBUS9/1cGfOFKyKf2+FzX1FFpNxL8zeWA3p6cjMo5oXfNNNbX",
	"F3qG9dxlbsLiNyxDjYrShgqjtlsEp63boGKHEeagcv1KdV6hrhj4VoSK7hbIoWo5fXkqX7J57tab9zZV",
	"73xbTWc01FVip0B6mXgn4NcN6SWQnLcotKVxrPMxwxCmERLGNwmQWbp1x3jZ6RFfGZbfg6xZfN316IIQ",
	"k4wdhuj2UPo9yLOU/PGm2Phei/95Djq7pew5u5OYUHc0tTUOn123jwrhVioovurJ8Gkla5lUspdN+Sk1",
	"1yzRlMQSuJrZrZRxhJFIIVRFXRc/H6M/1EVGRIQ5opu//kMgXag9buGyqFvuWufbjjf/U5lxF95ZCZTi",
	"zIPDWlbJB2qt9UBdzsejv5fmnSFqfHWhyv0Kq3nZgIPkBB4gGLU6LU17N1jtqSqYHPzW3c5HVq0BPBI5",
	"N60TVxffLybH9kJeszbliY/0/pyZF1ZEJs7fXi8wfUA6c3cND1DaCpRM4/xwJJ3r8SsCKXQvbx5H5/mF",
	"gAOQtgIkFdqZWkrWBqB6U9CKKMpSG0Z2omjJY936E6LeFqiXJUO1jO369w/YW817Kmyo2pwRiUt4Gp4w",
	"NSwq2N+ZbpCtp0DzQ5P+uh8i4tWFysV52CDZbr4RuEo4SJKACFaxFXlrYo/BaLZhDk/w7IcRaGkkXdUM",
	"FGT21wocCg0rJE+lFep9GenLK5aF8FHx9Y4BIV39DsHK51dNpvhySLnYsGKst36F9F6Y8GxqPsA2Ulhe",
	"Vm2mKMgVhA6B6VYCUwHyyHWz96mCbYlfUQMESP0HNRtidO+wX27496X4bI73ThcRghfEqfvqm74PhLuP",
	"w43vFkckGj/Z34dUytwNnMWyWUr7Yn+eMmdmZ5lKy6pvS9wqpiyjO0Gnu8v1g+JznGB+f4TFkft+RYc9",
	"/g3ze/e1DUyileGqpkRYoNQQWTdk/QBTk0Lkpt1tz9IPB7sp40c9xdeaPRS/MD6sBHuGQpYk+EiYb7pA",
	"hGJ7dbNoEp4BVXOBE7vo6LrJP4rvaXzpudnZrJqeVWvWZVYwzUHQw4zro9ip8a58uafDkAu12l1r1w8Q",
	"clQTNt2twZVkzcaAUv2kjEcWJTZeaW9wZy5g1OU7a59s31DHr+/D8MMTW+tFQScCUKg53f79hV9hgczN",
	"TpUAxjEHHC0QoSgThytqK6qGQR3CqPJ/dIYbsPFT/rM9MfUVrMp61J98LlHvTED3fHhrs1Wp16C0O0wi",
	"5Hu4F6WugxXZWElrSSvCXY2781BxY2vbG1Og4vNBLVk8oU8lrzb8HBDb2Czt5sKaaqJ0e8bRfhDVn5zd",
	"VRxzZlLahRUkEVBJpgR4bo9KHYDbtEdaLlH+GerXWGgfZnbGT+Z/RwwKWfxFDE+0YmjuT7vMXqrdDiMR",
	"rXeNIKRQv4O+bUDfBNDoiJT+l0W7Nyp91izYVNGu+n26jmyYLkHSFSvUh5TatkA28GLQD34naOOXGQ53",
	"btalCl1fETICPCZhJ+AN1q/OJ/3HJgnf5Dj/Bsvp02EDN7GBxR/rmn+tx6Cby8ln9W01USi4fbtpLK7V",
	"J68lIO0xiZBm730kjLV8/vr8/wEA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
