// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package rest

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorMessage string `json:"error_message"`
}

// NewEvent defines model for NewEvent.
type NewEvent struct {
	Contact struct {
		EmailAddress openapi_types.Email `json:"email_address"`
		Name         string              `json:"name"`
	} `json:"contact"`
	Event struct {
		From            string `json:"from"`
		Name            string `json:"name"`
		PubliclyVisible bool   `json:"publicly_visible"`
		To              string `json:"to"`
	} `json:"event"`
}

// AddEventJSONRequestBody defines body for AddEvent for application/json ContentType.
type AddEventJSONRequestBody = NewEvent
