// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package rest

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Admin_authScopes = "admin_auth.Scopes"
)

// Defines values for EventStatus.
const (
	EventStatusApproved          EventStatus = "approved"
	EventStatusAwaitingDocuments EventStatus = "awaiting documents"
	EventStatusCancelled         EventStatus = "cancelled"
	EventStatusProvisional       EventStatus = "provisional"
)

// Defines values for ListEventStatus.
const (
	ListEventStatusApproved          ListEventStatus = "approved"
	ListEventStatusAwaitingDocuments ListEventStatus = "awaiting documents"
	ListEventStatusCancelled         ListEventStatus = "cancelled"
	ListEventStatusProvisional       ListEventStatus = "provisional"
)

// AdminEventList defines model for AdminEventList.
type AdminEventList struct {
	Events []Event `json:"events"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorMessage string `json:"error_message"`
}

// Event defines model for Event.
type Event struct {
	Assignee     *openapi_types.Email `json:"assignee,omitempty"`
	Contact      string               `json:"contact"`
	Email        openapi_types.Email  `json:"email"`
	From         string               `json:"from"`
	Id           string               `json:"id"`
	KeyholderIn  *openapi_types.Email `json:"keyholderIn,omitempty"`
	KeyholderOut *openapi_types.Email `json:"keyholderOut,omitempty"`
	Name         string               `json:"name"`
	Status       EventStatus          `json:"status"`
	To           string               `json:"to"`
	Visible      bool                 `json:"visible"`
}

// EventStatus defines model for Event.Status.
type EventStatus string

// EventList defines model for EventList.
type EventList struct {
	Events []ListEvent `json:"events"`
}

// ListEvent defines model for ListEvent.
type ListEvent struct {
	From   string          `json:"from"`
	Id     string          `json:"id"`
	Name   string          `json:"name"`
	Status ListEventStatus `json:"status"`
	To     string          `json:"to"`
}

// ListEventStatus defines model for ListEvent.Status.
type ListEventStatus string

// NewEvent defines model for NewEvent.
type NewEvent struct {
	Contact struct {
		EmailAddress openapi_types.Email `json:"email_address"`
		Name         string              `json:"name"`
	} `json:"contact"`
	Event struct {
		From            string `json:"from"`
		Name            string `json:"name"`
		PubliclyVisible bool   `json:"publicly_visible"`
		To              string `json:"to"`
	} `json:"event"`
}

// SendInvoiceBody defines model for SendInvoiceBody.
type SendInvoiceBody struct {
	Contact openapi_types.Email `json:"contact"`

	// Events List of Event IDs that this invoice applies to.
	Events *[]string             `json:"events,omitempty"`
	Items  []SendInvoiceBodyItem `json:"items"`
}

// SendInvoiceBodyItem defines model for SendInvoiceBodyItem.
type SendInvoiceBodyItem struct {
	Cost        float32 `json:"cost"`
	Description string  `json:"description"`
	EventID     *string `json:"eventID,omitempty"`
}

// GetApiV1AdminEventsParams defines parameters for GetApiV1AdminEvents.
type GetApiV1AdminEventsParams struct {
	// From The date to obtain events from
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To The date to obtain events to
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// GetApiV1EventsParams defines parameters for GetApiV1Events.
type GetApiV1EventsParams struct {
	// From The date to obtain events from
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To The date to obtain events to
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// AddEventJSONRequestBody defines body for AddEvent for application/json ContentType.
type AddEventJSONRequestBody = NewEvent

// AdminSendInvoiceJSONRequestBody defines body for AdminSendInvoice for application/json ContentType.
type AdminSendInvoiceJSONRequestBody = SendInvoiceBody
