// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package rest

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ListEventStatus.
const (
	Approved    ListEventStatus = "approved"
	Provisional ListEventStatus = "provisional"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorMessage string `json:"error_message"`
}

// EventList defines model for EventList.
type EventList struct {
	Events []ListEvent `json:"events"`
}

// ListEvent defines model for ListEvent.
type ListEvent struct {
	From   string          `json:"from"`
	Id     string          `json:"id"`
	Name   string          `json:"name"`
	Status ListEventStatus `json:"status"`
	To     string          `json:"to"`
}

// ListEventStatus defines model for ListEvent.Status.
type ListEventStatus string

// NewEvent defines model for NewEvent.
type NewEvent struct {
	Contact struct {
		EmailAddress openapi_types.Email `json:"email_address"`
		Name         string              `json:"name"`
	} `json:"contact"`
	Event struct {
		From            string `json:"from"`
		Name            string `json:"name"`
		PubliclyVisible bool   `json:"publicly_visible"`
		To              string `json:"to"`
	} `json:"event"`
}

// GetApiV1AdminEventsParams defines parameters for GetApiV1AdminEvents.
type GetApiV1AdminEventsParams struct {
	// From The date to obtain events from
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To The date to obtain events to
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// GetApiV1EventsParams defines parameters for GetApiV1Events.
type GetApiV1EventsParams struct {
	// From The date to obtain events from
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To The date to obtain events to
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// AddEventJSONRequestBody defines body for AddEvent for application/json ContentType.
type AddEventJSONRequestBody = NewEvent
