apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: booking
                port:
                  number: 80
