apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  template:
    spec:
      containers:
        - name: booking
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:password@postgres.booking.svc.cluster.local:5432/postgres?sslmode=disable