apiVersion: v1
kind: Secret
metadata:
  name: booking-e2e-auth
type: Opaque
stringData:
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoZCI6InN0YXBsZWh1cnN0Z3VpZGluZy5vcmciLCJlbWFpbCI6InRlc3RAc3RhcGxlaHVyc3RndWlkaW5nLm9yZyJ9.19qix3TTBSjIXG9YU2Bj8OnvFZjB7awBkyS9saqOiE0"
