name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    outputs:
      version: ${{steps.semver.outputs.next}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go  
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Setup ko
        uses: ko-build/setup-ko@v0.6

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          patchAll: 'true '
          noVersionBumpBehavior: 'patch'

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
          commit: ${{ github.sha }}
          tag : ${{ steps.semver.outputs.next }}

      - name: Build container
        run:
          ko build ./cmd/booking --tags ${{steps.semver.outputs.next}} --tags latest --bare --platform=linux/amd64,linux/arm64

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'deploy/k8s/prod/kustomization.yaml'
          propertyPath: 'images[0].newTag'
          value: "${{steps.semver.outputs.next}}"
          commitChange: true
          message: "deploy: Booking ${{steps.semver.outputs.next}} [no ci]"   